steps:
# 步驟 1：構建 Docker 鏡像
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/test-gcp-cloud-build-cloud-run/test-gcp-cloud-build-and-cloud-run', '.']
# 步驟 2：推送鏡像到 Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/test-gcp-cloud-build-cloud-run/test-gcp-cloud-build-and-cloud-run']
# 'logsBucket' 欄位指定了 Cloud Build 將構建日誌儲存到的 Google Cloud Storage 儲存桶。
logsBucket: 'gs://test-gcp-cloud-build-and-cloud-run'